"""Custom RBAC chunker — structural splitter + PII isolation.

Migrated from the Phase-1 notebook ``02_chunking_strategies.ipynb`` (the
``custom_rbac_chunk`` function) with three architectural fixes identified
during the Phase 1-3 analysis:

1. **Overlapping-interval merge.** When a single line carries more than one
   PII pattern (typical in tabular ingest — a CSV row with both an IBAN and
   an email), Phase 1 emitted *one duplicate chunk per pattern* because each
   match independently extended itself to the full line. The new
   :meth:`CustomRBACChunker._merge_overlapping_intervals` collapses the
   line-extended spans into a single fused interval, so the line is emitted
   *once* with every detected sensitivity type tagged on the same chunk.

2. **Parent-child metadata.** Every emitted chunk carries
   ``parent_doc_id`` (the document-scoped UUID generated by the orchestrator)
   and ``chunk_index`` (a sequential counter within the document) so the
   Phase-2 parent-child reconstruction engine can stitch isolated PII
   fragments back to their source paragraph at retrieval time.

3. **Department inheritance.** The architectural distinction adopted at the
   end of Phase 3 Step 4 — ``department`` (single value, the parent
   document's home) vs. ``allowed_departments`` (list, the per-chunk RBAC
   read scope) — is enforced here. By default a chunk inherits its parent
   document's department: ``allowed_departments = [parent.department]``.
   Wider visibility (e.g., adding ``"hr"`` to a finance-owned expense
   policy) is the orchestrator's job (see TODO below).

----

ARCHITECTURAL CONSTRAINT — NO LLM CALLS HERE
============================================

This module is purely deterministic: structural split, regex match, interval
merge, fragment emission. It must remain free of any LLM call so unit tests
do not need Ollama, ingestion latency stays bounded by I/O, and the chunker
can be benchmarked in isolation.

TODO (deferred to ``application/ingestion_app.py``):
    Two human-in-the-loop / LLM steps belong to the orchestration layer:

    (1) Global metadata extraction for the *parent document*
        (``clearance_level``, ``department``, ``doc_type``, ``global_topic``)
        via an LLM call followed by Human-In-The-Loop confirmation in the
        UI. The result feeds the :class:`ChunkInput` consumed by this
        module.

    (2) Per-chunk *expansion* of ``allowed_departments`` from
        ``[parent.department]`` to a wider list. For instance, an expense
        policy owned by ``finance`` is also legitimately readable by
        ``hr``. Calling the LLM per-chunk introduces massive ingestion
        latency (~7 s/chunk × hundreds of chunks per document), so the
        orchestrator should batch, cache, or apply rule-based heuristics
        instead. This decision MUST stay outside the chunker so the
        chunker's behaviour is reproducible without external services.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Final, Pattern

from langchain_core.documents import Document

from core.exceptions import MetadataValidationError
from core.security import ClearanceLevel, Department
from domain.chunking.patterns import PII_PATTERNS, PIIPattern


# =============================================================================
# Configuration constants
# =============================================================================

# Structural separators tried, in order, by :meth:`_structural_split`. The
# splitter picks the separator that produces the most parts, falling back to
# the original text when none applies.
STRUCTURAL_SEPARATOR_PATTERNS: Final[list[str]] = [
    r"\n(?=\d+\.\s+[A-Z])",                                    # numbered sections "1. Title"
    r"\n(?=PRIMERA|SEGUNDA|TERCERA|CUARTA|QUINTA|CL[ÁA]USULAS)",  # legal contracts
    r"\n(?=\[\d{4}-)",                                         # log timestamps "[2026-…]"
    r"\n(?=Sheet:)",                                           # spreadsheet sheet markers
    r"\n(?=#{1,3}\s)",                                         # markdown headers
    r"\n\n",                                                   # double newline (paragraph break)
]

# Default minimum size in characters for a "structural" chunk; below this
# threshold, parts are merged with the previous one to avoid one-line micro
# chunks. Matches the Phase-1 default.
DEFAULT_MIN_CHUNK_SIZE: Final[int] = 80


# =============================================================================
# Input / internal data structures
# =============================================================================

@dataclass(frozen=True, slots=True)
class ChunkInput:
    """The metadata required to chunk a document.

    Built by ``application/ingestion_app.py`` after the global-metadata
    LLM step (and HITL confirmation) has assigned ``parent_clearance``,
    ``parent_department`` and ``parent_doc_id`` to the source document.

    Attributes:
        text:               The full text already extracted by
                            :class:`~domain.chunking.parsers.DocumentParser`.
        parent_doc_id:      A document-scoped UUID. Every emitted chunk
                            carries it so the Phase-2 parent-child
                            reconstruction can group the chunks of a
                            single source.
        parent_department:  The home department that determines which
                            *physical collection* the chunks of this
                            document live in. Must be a real
                            :class:`~core.security.Department` member;
                            the ``"all"`` wildcard is structurally
                            forbidden here and belongs in
                            ``allowed_departments`` only (post-init
                            guard enforces this at runtime).
        parent_clearance:   The base clearance every chunk inherits from
                            the document; per-chunk PII detection may
                            *raise* this but never lower it.
        source_file:        Original file name, propagated as metadata
                            for audit and the parent-child engine.
        page_number:        Optional page index (relevant for PDFs and
                            Excel sheets). Defaults to ``1``.
    """

    text: str
    parent_doc_id: str
    parent_department: Department
    parent_clearance: ClearanceLevel
    source_file: str
    page_number: int = 1

    def __post_init__(self) -> None:
        """Defence-in-depth: enforce at runtime what the type hints suggest.

        Python type annotations are advisory only — nothing prevents a
        caller from passing the string ``"all"`` (or any other value) into
        a field declared as :class:`Department`. This guard converts the
        implicit contract into an explicit, fail-fast :class:`
        ~core.exceptions.MetadataValidationError` with a diagnostic that
        names the architectural distinction:

          * ``department`` (this field) drives PHYSICAL collection routing
            and MUST be one of the seven real :class:`Department` members.
            The wildcard is invalid here because there is no ``"all"``
            collection in the production design.
          * ``allowed_departments`` (set later by the orchestrator) drives
            READ-permission scope and MAY include the ``"all"`` wildcard
            via :class:`~core.security.AllowedDepartment.ALL`.

        Raises:
            MetadataValidationError: if ``parent_department`` is not a
                :class:`Department` instance, or if ``parent_clearance``
                is not a :class:`ClearanceLevel` instance.
        """
        if not isinstance(self.parent_department, Department):
            raise MetadataValidationError(
                f"ChunkInput.parent_department must be a Department enum "
                f"(real corporate department), got {self.parent_department!r} "
                f"of type {type(self.parent_department).__name__}. "
                f"The 'all' wildcard is invalid for this field — it routes "
                f"chunks to a physical collection, and there is no 'all' "
                f"collection by design. Use AllowedDepartment.ALL inside the "
                f"`allowed_departments` list instead, after a real home "
                f"department has been chosen."
            )
        if not isinstance(self.parent_clearance, ClearanceLevel):
            raise MetadataValidationError(
                f"ChunkInput.parent_clearance must be a ClearanceLevel enum, "
                f"got {self.parent_clearance!r} of type "
                f"{type(self.parent_clearance).__name__}."
            )


@dataclass(frozen=True, slots=True)
class _DetectedSpan:
    """One PII match plus the boundaries of the line it lives on.

    Internal to the chunker. Not exported.
    """

    pattern_name: str
    match_start: int
    match_end: int
    line_start: int   # inclusive
    line_end: int     # exclusive
    min_clearance: ClearanceLevel


# =============================================================================
# The chunker
# =============================================================================

class CustomRBACChunker:
    """Structural splitter + PII isolator with RBAC-aware metadata.

    The pipeline applied to each document is:

      1. **Structural split** — paragraphs / sections / log entries via
         :data:`STRUCTURAL_SEPARATOR_PATTERNS`.
      2. **PII detection** — every part is scanned for the patterns in
         :data:`~domain.chunking.patterns.PII_PATTERNS`; each match is
         extended to its enclosing text line.
      3. **Interval merge** — the line-extended spans are fed through
         :meth:`_merge_overlapping_intervals` so a multi-PII row produces
         one fused interval rather than several duplicates.
      4. **Fragment emission** — for every fused interval the chunker
         emits one PII chunk (with the union of detected types and the
         maximum required clearance), plus one *remainder* chunk
         containing whatever text was outside any interval.
      5. **Metadata stamping** — every chunk receives ``parent_doc_id``,
         ``chunk_index``, ``department``, ``allowed_departments``,
         ``clearance_level``, ``contains_PII`` and ``sensitivity_types``.

    The class is stateless across :meth:`chunk` calls; instantiate once
    and reuse it for the whole ingestion process.
    """

    def __init__(
        self,
        patterns: list[PIIPattern] | None = None,
        *,
        min_chunk_size: int = DEFAULT_MIN_CHUNK_SIZE,
    ) -> None:
        """Initialise the chunker.

        Args:
            patterns:        The PII pattern set to apply. Defaults to the
                             canonical :data:`PII_PATTERNS` from the
                             patterns vault.
            min_chunk_size:  Minimum length, in characters, below which a
                             structural part is merged with the previous
                             one instead of becoming its own chunk.
        """
        self._patterns: list[PIIPattern] = list(patterns) if patterns is not None else list(PII_PATTERNS)
        self._min_chunk_size: int = min_chunk_size
        self._compiled_separators: list[Pattern[str]] = [
            re.compile(sep) for sep in STRUCTURAL_SEPARATOR_PATTERNS
        ]

    # ───────────────────────────── Public API ────────────────────────────────
    def chunk(self, doc: ChunkInput) -> list[Document]:
        """Run the full pipeline against ``doc`` and return its chunks.

        Args:
            doc: A populated :class:`ChunkInput`.

        Returns:
            The list of :class:`~langchain_core.documents.Document` chunks,
            in document order, with all metadata fields populated.
        """
        parts: list[str] = self._structural_split(doc.text)
        chunks: list[Document] = []
        chunk_idx: int = 0

        for part in parts:
            spans: list[_DetectedSpan] = self._find_sensitive_spans(part)

            # Easy case: no PII at all in this structural part.
            if not spans:
                chunks.append(self._make_chunk(
                    text=part,
                    doc=doc,
                    chunk_idx=chunk_idx,
                    contains_pii=False,
                    sensitivity_types=[],
                    clearance=doc.parent_clearance,
                ))
                chunk_idx += 1
                continue

            # Merge the line-extended spans BEFORE slicing, so a row with
            # multiple PII types yields a single isolated chunk rather than
            # several duplicates.
            line_intervals: list[tuple[int, int]] = [(s.line_start, s.line_end) for s in spans]
            merged_intervals: list[tuple[int, int]] = self._merge_overlapping_intervals(line_intervals)

            # For each fused interval, gather the contributing PII types
            # and the maximum clearance escalation they collectively imply.
            for interval_start, interval_end in merged_intervals:
                contributing = [
                    s for s in spans
                    if s.line_start < interval_end and s.line_end > interval_start
                ]
                if not contributing:
                    continue
                fragment_text: str = part[interval_start:interval_end].strip()
                if not fragment_text:
                    continue
                types: list[str] = sorted({s.pattern_name for s in contributing})
                fragment_clearance = max(
                    (s.min_clearance for s in contributing),
                    default=doc.parent_clearance,
                )
                # Severity ladder: the chunk holds at least its parent's
                # clearance and at least the highest PII escalation found.
                effective_clearance = ClearanceLevel(
                    max(int(fragment_clearance), int(doc.parent_clearance))
                )
                chunks.append(self._make_chunk(
                    text=fragment_text,
                    doc=doc,
                    chunk_idx=chunk_idx,
                    contains_pii=True,
                    sensitivity_types=types,
                    clearance=effective_clearance,
                ))
                chunk_idx += 1

            # Build the remainder: everything in `part` that is OUTSIDE
            # any merged interval. The remainder inherits the parent's
            # clearance unchanged because no PII fired on it.
            remainder_pieces: list[str] = []
            cursor: int = 0
            for interval_start, interval_end in merged_intervals:
                if interval_start > cursor:
                    piece = part[cursor:interval_start].strip()
                    if piece:
                        remainder_pieces.append(piece)
                cursor = interval_end
            if cursor < len(part):
                piece = part[cursor:].strip()
                if piece:
                    remainder_pieces.append(piece)

            if remainder_pieces:
                remainder_text = "\n".join(remainder_pieces)
                chunks.append(self._make_chunk(
                    text=remainder_text,
                    doc=doc,
                    chunk_idx=chunk_idx,
                    contains_pii=False,
                    sensitivity_types=[],
                    clearance=doc.parent_clearance,
                ))
                chunk_idx += 1

        return chunks

    # ───────────────────────────── Internals ─────────────────────────────────
    def _structural_split(self, text: str) -> list[str]:
        """Apply each structural separator and pick the most expressive split.

        Returns the original text wrapped in a single-element list when no
        separator matches.
        """
        best: list[str] = [text]
        for separator in self._compiled_separators:
            parts = [p.strip() for p in separator.split(text) if p.strip()]
            if len(parts) <= 1:
                continue
            merged: list[str] = []
            buffer: str = ""
            for part in parts:
                if buffer and len(buffer) >= self._min_chunk_size:
                    merged.append(buffer)
                    buffer = part
                else:
                    buffer = (buffer + "\n" + part).strip() if buffer else part
            if buffer:
                merged.append(buffer)
            if len(merged) > len(best):
                best = merged
        return best

    def _find_sensitive_spans(self, text: str) -> list[_DetectedSpan]:
        """Find every PII match in ``text`` and extend each to its line."""
        spans: list[_DetectedSpan] = []
        for pattern in self._patterns:
            for match in pattern.compiled.finditer(text):
                # Extend match boundaries to the surrounding line so a CSV
                # row with multiple PII types ends up as one merged interval.
                prev_newline = text.rfind("\n", 0, match.start())
                line_start = prev_newline + 1 if prev_newline != -1 else 0
                next_newline = text.find("\n", match.end())
                line_end = next_newline if next_newline != -1 else len(text)
                spans.append(_DetectedSpan(
                    pattern_name=pattern.name,
                    match_start=match.start(),
                    match_end=match.end(),
                    line_start=line_start,
                    line_end=line_end,
                    min_clearance=pattern.min_clearance,
                ))
        return spans

    @staticmethod
    def _merge_overlapping_intervals(spans: list[tuple[int, int]]) -> list[tuple[int, int]]:
        """Collapse overlapping or touching intervals into their union.

        The classical "merge sorted intervals" algorithm. Solves the
        Phase-1 CSV-fragmentation issue: when multiple PII patterns hit
        the same line, each match independently extended itself to the
        whole line, producing duplicate intervals. After merging, the
        line appears exactly once in the output.

        Args:
            spans: A list of ``(start, end)`` tuples. ``end`` is exclusive
                so the algorithm naturally handles touching intervals
                (e.g., ``(0, 5)`` and ``(5, 10)`` merge to ``(0, 10)``).

        Returns:
            The merged list of disjoint intervals, sorted by ``start``.
            Empty input returns an empty list.

        Examples:
            >>> CustomRBACChunker._merge_overlapping_intervals(
            ...     [(0, 50), (0, 50), (10, 60)]
            ... )
            [(0, 60)]
            >>> CustomRBACChunker._merge_overlapping_intervals(
            ...     [(0, 30), (40, 80)]
            ... )
            [(0, 30), (40, 80)]
        """
        if not spans:
            return []
        sorted_spans = sorted(spans, key=lambda s: (s[0], s[1]))
        merged: list[list[int]] = [list(sorted_spans[0])]
        for start, end in sorted_spans[1:]:
            last_start, last_end = merged[-1]
            if start <= last_end:                       # overlap or touch
                merged[-1][1] = max(last_end, end)
            else:                                        # gap → new interval
                merged.append([start, end])
        return [(s, e) for s, e in merged]

    @staticmethod
    def _make_chunk(
        *,
        text: str,
        doc: ChunkInput,
        chunk_idx: int,
        contains_pii: bool,
        sensitivity_types: list[str],
        clearance: ClearanceLevel,
    ) -> Document:
        """Build a :class:`Document` with the canonical metadata schema."""
        metadata: dict[str, object] = {
            # Parent-child reconstruction keys
            "parent_doc_id":       doc.parent_doc_id,
            "chunk_index":         chunk_idx,
            "source_file":         doc.source_file,
            "page_number":         doc.page_number,

            # Routing key — single value; the document's home department.
            "department":          doc.parent_department.value,

            # Inheritance rule (see module docstring TODO):
            # `allowed_departments` defaults to [parent.department].
            # Expansion to a wider list (or the "all" wildcard) is the
            # orchestrator's responsibility, not the chunker's.
            "allowed_departments": [doc.parent_department.value],

            # RBAC severity (max of parent and PII escalation)
            "clearance_level":     int(clearance),

            # Detection results
            "contains_PII":        contains_pii,
            "sensitivity_types":   list(sensitivity_types),
        }
        return Document(page_content=text, metadata=metadata)
